version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stori
    ports:
      - "5432:5432"
  backend:
    build: ./StoriNewsletter
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./StoriNewsletter:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    build: ./StoriNewsletterFront
    command: npm run dev -- --host
    volumes:
      - ./StoriNewsletterFront:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
