# Generated by Django 5.0.1 on 2024-01-27 22:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('sent', 'Sent'), ('scheduled', 'Scheduled')], max_length=250, verbose_name='Tipo de evento')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Correo destinatario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
            ],
            options={
                'db_table': 'newsletter_history',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Titulo')),
                ('recipients_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='Correos destinatarios')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Link origen')),
                ('email_template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plantilla de correo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
    ]
