# Generated by Django 5.0.1 on 2024-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='source_url',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='source_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre clave'),
        ),
    ]
