# Generated by Django 5.0.1 on 2024-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletterhistory_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
